order=[]
order.append("Codingal")
order.append("Pragyan")
order.append("Basob")
order.append(98)
order.append(95)
print(order)
list1=[7,9,0,4,3,9]
print(list1)
list2=list1*4
print(list2)
print(list1[::-1])
print(order[::-1])
